image: docker:latest

variables:
  LATEST_VER_BOT_PROD: caleberios/gaia:latest
  LATEST_VER_ACTION_PROD: caleberios/gaia-actions:latest
  LATEST_VER_BOT_HML: caleberios/gaia:homolog
  LATEST_VER_ACTION_HML: caleberios/gaia-actions:homolog

stages:
  - build
  - quality
  - pushImage
  - deploy

build bot:
  stage: build
  services:
    - docker:dind
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose up bot

staticAnalysis:
  stage: quality
  image: ejplatform/python:alpine
  script:
    - flake8

pushHomolog:
  stage: pushImage
  services:
    - docker:dind
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_BOT_HML -f docker/bot.Dockerfile .
    - docker build -t $LATEST_VER_ACTION_HML -f docker/actions.Dockerfile .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_BOT_HML && docker image rm $LATEST_VER_BOT_HML
    - docker push $LATEST_VER_ACTION_HML && docker image rm $LATEST_VER_ACTION_HML

pushProd:
  stage: pushImage
  services:
    - docker:dind
  only:
    - master
  script:
    - docker build -t $LATEST_VER_BOT_PROD -f docker/bot.Dockerfile .
    - docker build -t $LATEST_VER_ACTION_PROD -f docker/actions.Dockerfile .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_BOT_PROD && docker image rm $LATEST_VER_BOT_PROD
    - docker push $LATEST_VER_ACTION_PROD && docker image rm $LATEST_VER_ACTION_PROD

deployHomolog:
  stage: deploy
  image: google/cloud-sdk
  only:
    - dev
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete -f k8s/gaia_actions_hml.yaml
    - kubectl delete -f k8s/gaia_hml.yaml
    - kubectl apply -f k8s/gaia_actions_hml.yaml
    - kubectl apply -f k8s/gaia_hml.yaml

deployProd:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete -f k8s/gaia_actions.yaml
    - kubectl delete -f k8s/gaia.yaml
    - kubectl apply -f k8s/gaia_actions.yaml
    - kubectl apply -f k8s/gaia.yaml
