image: docker:latest

services:
  - docker:dind

variables:
  LATEST_VER_BOT_PROD: caleberios/gaia:latest
  LATEST_VER_ACTION_PROD: caleberios/gaia-actions:latest
  LATEST_VER_BOT_FB: caleberios/gaia:facebook
  LATEST_VER_BOT_HML: caleberios/gaia:homolog
  LATEST_VER_ACTION_HML: caleberios/gaia-actions:homolog

stages:
  - build
  - train
  - quality
  - pushImage
  - deploy

buildBot:
  stage: build
  script:
    - docker build -f docker/bot.Dockerfile .

buildActions:
  stage: build
  script:
    - docker build -f docker/actions.Dockerfile .

trainBot:
  stage: train
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose run --rm bot make train

staticAnalysis:
  stage: quality
  image: ejplatform/python:alpine
  script:
    - flake8

pushHomolog:
  stage: pushImage
  services:
    - docker:dind
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_BOT_HML -f docker/bot.Dockerfile .
    - docker build -t $LATEST_VER_ACTION_HML -f docker/actions.Dockerfile .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_BOT_HML && docker image rm $LATEST_VER_BOT_HML
    - docker push $LATEST_VER_ACTION_HML && docker image rm $LATEST_VER_ACTION_HML

pushProd:
  stage: pushImage
  services:
    - docker:dind
  only:
    - master
  script:
    - docker build -t $LATEST_VER_BOT_PROD -f docker/bot.Dockerfile .
    - docker build -t $LATEST_VER_ACTION_PROD -f docker/actions.Dockerfile .
    - cat docker/bot.Dockerfile | sed "s/telegram/facebook/g" | docker build -t $LATEST_VER_BOT_FB -f - .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_BOT_PROD && docker image rm $LATEST_VER_BOT_PROD
    - docker push $LATEST_VER_ACTION_PROD && docker image rm $LATEST_VER_ACTION_PROD
    - docker push $LATEST_VER_BOT_FB && docker image rm $LATEST_VER_BOT_FB

deployHomolog:
  stage: deploy
  image: google/cloud-sdk
  only:
    - dev
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete service/gaia-bot-hml deployment.apps/gaia-bot-hml
    - kubectl delete service/gaia-actions-hml deployment.apps/gaia-actions-hml
    - kubectl apply -f k8s/gaia_actions_hml.yaml
    - cat k8s/gaia_hml.yaml | sed "s/{{API_KEY_HML}}/$API_KEY_HML/g" | kubectl apply -f -

deployProd:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete service/gaia-bot deployment.apps/gaia-bot
    - kubectl delete service/gaia-actions deployment.apps/gaia-actions
    - kubectl delete service/gaia-bot-fb deployment.apps/gaia-bot-fb
    - kubectl apply -f k8s/gaia_actions.yaml
    - cat k8s/gaia.yaml | sed "s/{{API_KEY}}/$API_KEY/g" | kubectl apply -f -
    - cat k8s/gaia_fb.yaml | sed "s/{{FB_VERIFY}}/$FB_VERIFY/g" | sed "s/{{FB_SECRET}}/$FB_SECRET/g" | | sed "s/{{FB_ACCESS_TOKEN}}/$FB_ACCESS_TOKEN/g" kubectl apply -f -
