apiVersion: v1
kind: Service
metadata:
  name: gaia-bot
spec:
  ports:
  - port: 443
    targetPort: 5001
  selector:
    app: gaia-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-bot
spec:
  selector:
    matchLabels:
      app: gaia-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: gaia-bot
    spec:
      containers:
      - env:
        - name: TELEGRAM_TOKEN
          value: {{API_KEY}}
        - name: TELEGRAM_WEBHOOK
          value: https://bot.botgaia.ga/webhooks/telegram/webhook
        - name: TELEGRAM_BOT_USERNAME
          value: DeusaGaiaBot
        - name: ENDPOINT_ACTIONS
          value: https://bot.actions.botgaia.ga/webhook
        - name: ENVIRONMENT
          value: production
        image: caleberios/gaia:latest
        imagePullPolicy: Always
        name: gaia-bot
        ports:
        - containerPort: 5001